language: java
sudo: required
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
os:
- linux
install: true
script: mvn -q clean install
before_deploy:
- bash ./ci/before_deploy.sh
deploy:
  provider: script
  script: bash ./ci/deploy.sh
  on:
    branch: master
    tags: true
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email: dev-notify@lockss.org
before_install:
- openssl aes-256-cbc -K $encrypted_63c142cb3b3e_key -iv $encrypted_63c142cb3b3e_iv
  -in ci/codesigning.asc.enc -out ci/codesigning.asc -d

env:
  global:
  - secure: Bcs/jRI9qIGa4wYBTNkS/qb1ji1Tb7d8LE5w50JBqiEaIVl82EhrgfMuJlLJPjbf3vBZNAhYOXGnNZR+H4Vi9nZ6uE02FS0jvhgBHLbif7Pcy7x7LtDyooluKKOVBJxIMU4XysZGXQarGr9o1oeuMxH8B0o5SqBWoueuzWikIl5jSEgkVAi/qINb3ridWHSPNlUHoowhnFD3D/RMBytkvBRPFqXGfriityG1afMEGkIJPeP7FZ5Ad8uAcYlfTXNXgLn5LK/fVeuUS4fBpza2cXyLkicQahey+9epWw07tPSDNB6WqW8a0NwqNN8DC1WY9xM/WxUsfb4j20MjXNBrSVHvsTv3/7xviUbZlgmrFCxG1tf4Jtcbk2rNtd78I25DrMLCFect6bhAUWGncmXRcKNkFx9LQRD/imoMVPi3sEQAEUu5Sszv5xSC3twG0U5HBZO31Mx/EhrJZ42imoS73mweftzTB32P/S8Z2TtTj/qM7FgoqewBwqN2XlZ5WnEOSmn9UF5e1ef5aZkZHa66LryatLLqxcyq7g5GeWjCXLga6cIgJQwk8GWAfAwxBiiyV0PzU4QUw96gqfhYFfth08o8v87gqOUOoQ3YOoTmP92D6YVC6A79MW2LgmuU2I01wxTlRD9c8RGvr/MqT6E+m4vTzZXdB6kkwqLggCCl8Yk=
  - secure: Qpe2WNd5HTV8fOOoumZajLb0Di8l8deFQS3Y3+q89vKeyDyd+pysGCNOFS3Is9YxgUJQr9o9MbzfdR5jTmpfoJln/pjfDj/7EsVKLOKk+Ex+FI4TvhtcAnXxfeUe/NgzFkr2iY7ijw5jpYUlwTkxj79J1Ilzoj0iNCiwlw5r+UqQGgnxVgwkG5W4H7Y73cv1e08p8OdPWY+SzjkxCuJUiKVM9+AgixOtXYhZ6AcDPvOPW1avMHhg+feyxPHFug2LMIznJtn8wuJhefSfXX6wxNKPGcR3QwCsHd7ZU/zO4zDfgvB+pouypb/zRRIDDlYKpZ+vS0fQq/cFOYrnOMba8rMca4gGq1rezHXis0npxbimoFVfxNLcS44ZbyCmMIUniRTU5l35C2AnDQEoEnbu8oC/9oqh/XxYbqjkgRkrGA4GiJ5HKERVG8NCWhN2m5H3D3xmBPaP4OtWZH5MhIjZXnLQFkrn4GFy0K1neystJu7czzU9JkFUkWJ3fodwF4WUSW9mNPv9m2mORkCA18nQdX9aHSmyA5A/plEk2obB0PUZDPnSMM97nL9DFk69OOfo8SYZSFXi4bUUzYlI2+ZXKj7mWL5iDZAPat/SSz/iDUKjo+76FameiKUcVVk8yfr/XyxSMAN9FGWvbC2FqTIznmqj8FutqrhnrmzLM86sslc=
  - secure: bMLAf7XUUMCCj5kyjmD1VtXKvHAqZ250xBV1IJs8N5A7W8jh4y4bxydkeccE5NinV631zutc1wXtvqRlNJe5qgBhg6ebBZXwE9TMBB5GRLuWl3iZSYTIDFFWxxWLUIqfdKlQvdY8+lYM3YlVPfcVqP//bCnHMn5mGp4qYiqDCsEv/mJsYL44DKC+OYTnIcdM3HXjKAhF6z39Xk4bRqlrkSvsr+mMqDtEe16A/N0KudXRolKJidQPVVFKUbfsFjqr+l0g3Oq79XVrgsW2nncaFE184GFGezU1rP8L77X8G8Q6kq4Bdgejq/t09t01BhCJRl2/1Mq1RoXZeIq+CTLo1UOi4BuMNhA18S5vyVFkmW6FCPjAmTjS6Lc2mg8NZvdW0jSpj+VnKmqDa6rpGgold/tJiBStTME96yZcnfl1xD1jaYdg56jkuXcDz0XKevbVK48TXK6lvWcECUOgFapcU2WUlxD8loHIwKBG+NLdO2UYJiY/mo8eCmQLA2kwBVH7vBmFfTwPyDlbTRKR7AdN+C/TdBQ1S+9tSSIPPJc2AeuHLJ/yV246Z5VHzQSr08gmkB/zmq14Zam0vzUcO+EBjusW/PBnXFxhxTQURnf3wx7WekmWycWXBco7/qHN07y3jfQvwMiQm4/+fnv5jNYeRtYTo5n8wHSOT7KQu8bFQg0=
  - secure: ophv1pbrACTgXIPwbrdYZUvdn/SytQMxxkoykkCd8ta3zT91ba602rCuh6/dSmN9t3qgQj+AvFPhjo5E6ZlQzsO+hnTQEilaXgzx9FDwKV1zWCNryFJG5iXoXTKkNXI/55D1S/8nLvIXxGXOMZqoWCM292ZdLNo98P6udFW6qbGwZEaVRr55JD7KCjqqQQw8xB3ZMDVbZTVjq41F08dUkhN7yCQ81Edc8DNTtBG1yvO6kdhU9/pX3JQWIkIzKT+wCIUpvpQCdLvSTq5EnqYmcCUqvaiiVGRQs1udoelXsYsLIVdETpiw7+WQEh0PlT004mD58MWXFUnlRlZePkPtPFUIfh1NZw0NBC3C6S+02qzXnFAtJHfYqaDNDGotDdPFA5oAUg1wVoDoDLZqj8q2ZC+1CtwT4DA27jFqhzGXp7iedAV2P7nh1T+VNsZUUkDmNNaAv9ykpuAQuVol3lvsVyX2/rMREgvLYu1RR5htWm+bR76wdfhJqsAJd4YUEDY6oq5ud+dNaVvqBWnPVn+kJV189wl0VQILtsPItPgCqlbXWWjpEhHkb+mFAj2L0zcM9sxyD9fOq1NfDhWrmin5YFhlqW5bP8wbiGRBo1QDmsncWSJOQ+uLEjJV2PVhMRSXFOtFP1ZqqwA7I766BqhJNSvNh62zgSZ/rwNDzEzDgtw=
  - secure: E526XtTBf1eYL5YaO0H3COwtsSyT+7vZliKgeG5fxMzlRD1lacZEftTRKd4S0E7qhrWQOxcXNJWpMEM7BnoXUyW2E6k0nRwp72758tAmL9AHN7zj02Gk5FBa38wGAyOx3/09lYF8cNs2xXQsVIHKGhwtr9o6G7nLErMQ22Y4UhlDKvITVX31DTkAI+4Kz0R8o17yc2szOKfWiHvpY4oC2Vb5s8HUzowaE84HhOQV/ku8Q5aZrPGLd/YvJf37mdnwRxuAEb+6gBkVYqVMSYNApDz13R8uvyJNfDiy+/ceP4hKTBxSuXFWpnhzwomtzuv5+CvDOjfjBSDYil4aFuUybuEoXnbLdnKK+6izk4I8ktE5/8/mSTszaWQcy2Ncl6Kv6o+4nO8kfkxEgWBnu1NwpqTOUsdTE2UFBo7HDL9nz2Jv+kbgcvlyb/G2N7TX6jDPy56avlx/yqnlu+0JbAyWR8JSk+lEaNgVT9S7VEa6qxYCfSrpFXSYGqMmY7Ljj2vw3uGEshUbt/0sUesWqGvHpyRRmnAQ00ZZsJaINDVMeNXwH6Fgh7lQGV6VgNqbklmhu5cx99HzeoxjNYxb5rV4QlSppwMO/WvSpCh3aLtpuCBSZDfRDiyVmIEfObkqHYURbZ2VIYSm4GQcP6QylY52eMy5bwjFRTQo78mwZdMIH4g=
  - secure: TlYIY1RrdjJhhEBl0ElnFd+byqd5Ie/WN9bwLs++WwDKYmPj7PamkfjImvCJSPwdPdvx/kDc/IQ2m3k14Xmd6ByjHAdHWto5ZtQhtKSroyYJplyYaR+XbkTl3KIzqP1RWFK3Q5FYPMv8EXN+pB0x5hbiqx/iNIckWYvznk83Qj1rgEUyxPNbGd9lKZyUQKiL2RJzhbIjNIpQNkvesu1e074olupHHbr5OgSJ/cM1bAinYYv1sJuSifyxleLnqWAJ5BWxIvMfpIagYlkkIhWOywUJFCcTyj70QBykNwsSmt0jne+GnR01+mVzk1fD4fw+XutgDuYs+SFThjOgfPsn42UvLrlv84/6V+bR5JEt0mg/Edr3wX8sgnkGogEaZU/vRn1xJG4TM3TejUKehAbZZAs7YunP4os4X0moebvHE6sRKoBzwRyNlfTz4PpKrj/aLDV/LteWWGwLc0fJFksiipnhOkVjK7+SsLgYR4etHbdPSea4ro9HG/7mnHiVJP+EmeV8QoNtttfMDZ0Ma1+XfjKQjoCmpPj4rHgucH6cfb3JLgYzgZ1ftDGk2jK9WKAszdHk/GeIRDeY9LQHLuO/iEM70+bZ7SDj/MYl/GINytK+N1mElON9vLY7r+MKmyagEcIp8jiMZjenJA/3LpBrF9N71NYa/U4vwevmb50OVVY=
