#!/bin/bash

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Fixes the code generated by Swagger Codegen.

function fixImport() {
JAVA_SRC=$1
sed -i.backup "s/import $2/import $3/" $JAVA_SRC && rm $JAVA_SRC.backup
}

function fixResponseCode1234() {
JAVA_SRC=$1
sed -i.backup 's/responseCode = "1234"/responseCode = "default"/' $JAVA_SRC && rm $JAVA_SRC.backup
}

# Support both Maven (src/generated/java) and Gradle (build/generated/sources/openapi/src/main/java) paths
GENERATED_DIR="${GENERATED_DIR:-src/generated/java}"
API_DIR="${GENERATED_DIR}/org/lockss/laaws/poller/api"
MODEL_DIR="${GENERATED_DIR}/org/lockss/laaws/poller/model"

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=${API_DIR}/StatusApiDelegate.java
fixImport $STATUS_API_DELEGATE org.lockss.laaws.poller.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit StatusApi.java.
STATUS_API=${API_DIR}/StatusApi.java
fixImport $STATUS_API org.lockss.laaws.poller.model.ApiStatus org.lockss.util.rest.status.ApiStatus
fixResponseCode1234 $STATUS_API

# Edit StatusApiController.java.
STATUS_API_CONTROLLER=${API_DIR}/StatusApiController.java
fixImport $STATUS_API_CONTROLLER org.lockss.laaws.poller.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit PollsApiDelegate.java.
POLLS_API_DELEGATE=${API_DIR}/PollsApiDelegate.java
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary

# Edit PollsApi.java.
POLLS_API=${API_DIR}/PollsApi.java
fixImport $POLLS_API org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc
fixImport $POLLS_API org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary
fixResponseCode1234 $POLLS_API

# Edit PollsApiController.java.
POLLS_API_CONTROLLER=${API_DIR}/PollsApiController.java
fixImport $POLLS_API_CONTROLLER org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc
fixImport $POLLS_API_CONTROLLER org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary

# Edit PollerDetail.java.
POLLER_DETAIL=${MODEL_DIR}/PollerDetail.java
fixImport $POLLER_DETAIL org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc

# Edit VoterDetail.java.
VOTER_DETAIL=${MODEL_DIR}/VoterDetail.java
fixImport $VOTER_DETAIL org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc

# Edit WsApiDelegate.java.
WS_API_DELEGATE=${API_DIR}/WsApiDelegate.java
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.HasherWsParams org.lockss.ws.entities.HasherWsParams
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.PollWsResult org.lockss.ws.entities.PollWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.PeerWsResult org.lockss.ws.entities.PeerWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.RepositorySpaceWsResult org.lockss.ws.entities.RepositorySpaceWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.RepositoryWsResult org.lockss.ws.entities.RepositoryWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.VoteWsResult org.lockss.ws.entities.VoteWsResult

# Edit WsApi.java.
WS_API=${API_DIR}/WsApi.java
fixImport $WS_API org.lockss.laaws.poller.model.HasherWsParams org.lockss.ws.entities.HasherWsParams
fixImport $WS_API org.lockss.laaws.poller.model.PeerWsResult org.lockss.ws.entities.PeerWsResult
fixImport $WS_API org.lockss.laaws.poller.model.PollWsResult org.lockss.ws.entities.PollWsResult
fixImport $WS_API org.lockss.laaws.poller.model.RepositorySpaceWsResult org.lockss.ws.entities.RepositorySpaceWsResult
fixImport $WS_API org.lockss.laaws.poller.model.RepositoryWsResult org.lockss.ws.entities.RepositoryWsResult
fixImport $WS_API org.lockss.laaws.poller.model.VoteWsResult org.lockss.ws.entities.VoteWsResult
fixResponseCode1234 $WS_API

# Edit Model dependencies
# PeerData
PEER_DATA=${MODEL_DIR}/PeerData.java
fixImport $PEER_DATA org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# RepairQueue
REPAIR_QUEUE=${MODEL_DIR}/RepairQueue.java
fixImport $REPAIR_QUEUE org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# TallyData
TALLY_DATA=${MODEL_DIR}/TallyData.java
fixImport $TALLY_DATA org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# VoterSummary
VOTER_SUMMARY=${MODEL_DIR}/VoterSummary.java
fixImport $VOTER_SUMMARY org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# PollerPager
POLLER_PAGER=${MODEL_DIR}/PollerPager.java
fixImport $POLLER_PAGER org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary

# AUsApi.java
AUS_API=${API_DIR}/AusApi.java
fixResponseCode1234 $AUS_API

# Remove generated model files that already exist in lockss-util-rest
# These are shared DTOs that should come from lockss-util-rest, not be regenerated
rm -f ${MODEL_DIR}/PollerSummary.java
rm -f ${MODEL_DIR}/PollDesc.java
rm -f ${MODEL_DIR}/LinkDesc.java
rm -f ${MODEL_DIR}/ApiStatus.java
