#!/bin/bash

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Fixes the code generated by Swagger Codegen.

function fixImport() {
JAVA_SRC=$1
sed -i.backup "s/import $2/import $3/" $JAVA_SRC && rm $JAVA_SRC.backup
}

function fixResponseCode1234() {
JAVA_SRC=$1
sed -i.backup 's/responseCode = "1234"/responseCode = "default"/' $JAVA_SRC && rm $JAVA_SRC.backup
}

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=src/generated/java/org/lockss/laaws/poller/api/StatusApiDelegate.java
fixImport $STATUS_API_DELEGATE org.lockss.laaws.poller.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit StatusApi.java.
STATUS_API=src/generated/java/org/lockss/laaws/poller/api/StatusApi.java
fixImport $STATUS_API org.lockss.laaws.poller.model.ApiStatus org.lockss.util.rest.status.ApiStatus
fixResponseCode1234 $STATUS_API

# Edit PollsApiDelegate.java.
POLLS_API_DELEGATE=src/generated/java/org/lockss/laaws/poller/api/PollsApiDelegate.java
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.PollerPageInfo org.lockss.util.rest.poller.PollerPageInfo
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.RepairData org.lockss.util.rest.poller.RepairData
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.RepairPageInfo org.lockss.util.rest.poller.RepairPageInfo
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.RepairTypeEnum org.lockss.util.rest.poller.model.RepairTypeEnum
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.TallyTypeEnum org.lockss.util.rest.poller.model.TallyTypeEnum
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.UrlPageInfo org.lockss.util.rest.poller.UrlPageInfo
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.VoterPageInfo org.lockss.util.rest.poller.VoterPageInfo
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.VoterSummary org.lockss.util.rest.poller.VoterSummary
fixImport $POLLS_API_DELEGATE org.lockss.laaws.poller.model.VoterUrlsEnum org.lockss.util.rest.poller.model.VoterUrlsEnum

# Edit PollsApi.java.
POLLS_API=src/generated/java/org/lockss/laaws/poller/api/PollsApi.java
fixImport $POLLS_API org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc
fixImport $POLLS_API org.lockss.laaws.poller.model.PollerPageInfo org.lockss.util.rest.poller.PollerPageInfo
fixImport $POLLS_API org.lockss.laaws.poller.model.PollerSummary org.lockss.util.rest.poller.PollerSummary
fixImport $POLLS_API org.lockss.laaws.poller.model.RepairData org.lockss.util.rest.poller.RepairData
fixImport $POLLS_API org.lockss.laaws.poller.model.RepairPageInfo org.lockss.util.rest.poller.RepairPageInfo
fixImport $POLLS_API org.lockss.laaws.poller.model.RepairTypeEnum org.lockss.util.rest.poller.model.RepairTypeEnum
fixImport $POLLS_API org.lockss.laaws.poller.model.TallyTypeEnum org.lockss.util.rest.poller.model.TallyTypeEnum
fixImport $POLLS_API org.lockss.laaws.poller.model.UrlPageInfo org.lockss.util.rest.poller.UrlPageInfo
fixImport $POLLS_API org.lockss.laaws.poller.model.VoterPageInfo org.lockss.util.rest.poller.VoterPageInfo
fixImport $POLLS_API org.lockss.laaws.poller.model.VoterSummary org.lockss.util.rest.poller.VoterSummary
fixImport $POLLS_API org.lockss.laaws.poller.model.VoterUrlsEnum org.lockss.util.rest.poller.model.VoterUrlsEnum
fixResponseCode1234 $POLLS_API

# Edit PollerDetail.java.
POLLER_DETAIL=src/generated/java/org/lockss/laaws/poller/model/PollerDetail.java
fixImport $POLLER_DETAIL org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc

# Edit VoterDetail.java.
VOTER_DETAIL=src/generated/java/org/lockss/laaws/poller/model/VoterDetail.java
fixImport $VOTER_DETAIL org.lockss.laaws.poller.model.PollDesc org.lockss.util.rest.poller.PollDesc

# Edit WsApiDelegate.java.
WS_API_DELEGATE=src/generated/java/org/lockss/laaws/poller/api/WsApiDelegate.java
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.HasherWsParams org.lockss.ws.entities.HasherWsParams
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.PollWsResult org.lockss.ws.entities.PollWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.PeerWsResult org.lockss.ws.entities.PeerWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.RepositorySpaceWsResult org.lockss.ws.entities.RepositorySpaceWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.RepositoryWsResult org.lockss.ws.entities.RepositoryWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.poller.model.VoteWsResult org.lockss.ws.entities.VoteWsResult

# Edit WsApi.java.
WS_API=src/generated/java/org/lockss/laaws/poller/api/WsApi.java
fixImport $WS_API org.lockss.laaws.poller.model.HasherWsParams org.lockss.ws.entities.HasherWsParams
fixImport $WS_API org.lockss.laaws.poller.model.PeerWsResult org.lockss.ws.entities.PeerWsResult
fixImport $WS_API org.lockss.laaws.poller.model.PollWsResult org.lockss.ws.entities.PollWsResult
fixImport $WS_API org.lockss.laaws.poller.model.RepositorySpaceWsResult org.lockss.ws.entities.RepositorySpaceWsResult
fixImport $WS_API org.lockss.laaws.poller.model.RepositoryWsResult org.lockss.ws.entities.RepositoryWsResult
fixImport $WS_API org.lockss.laaws.poller.model.VoteWsResult org.lockss.ws.entities.VoteWsResult
fixResponseCode1234 $WS_API

# Edit Model dependencies
# PeerData
PEER_DATA=src/generated/java/org/lockss/laaws/poller/model/PeerData.java
fixImport $PEER_DATA org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# RepairQueue
REPAIR_QUEUE=src/generated/java/org/lockss/laaws/poller/model/RepairQueue.java
fixImport $REPAIR_QUEUE org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# TallyDaTa
TALLY_DATA=src/generated/java/org/lockss/laaws/poller/model/TallyData.java
fixImport $TALLY_DATA org.lockss.laaws.poller.model.LinkDesc org.lockss.util.rest.poller.LinkDesc

# AUsApi.java
AUS_API=src/generated/java/org/lockss/laaws/poller/api/AusApi.java
fixImport $AUS_API org.lockss.laaws.poller.model.ExportFilenameTranslationEnum org.lockss.util.rest.poller.model.ExportFilenameTranslationEnum
fixImport $AUS_API org.lockss.laaws.poller.model.ExportFileTypeEnum org.lockss.util.rest.poller.model.ExportFileTypeEnum
fixResponseCode1234 $AUS_API

# AUsApi.java
AUS_API_DELEGATE=src/generated/java/org/lockss/laaws/poller/api/AusApiDelegate.java
fixImport $AUS_API_DELEGATE org.lockss.laaws.poller.model.ExportFilenameTranslationEnum org.lockss.util.rest.poller.model.ExportFilenameTranslationEnum
fixImport $AUS_API_DELEGATE org.lockss.laaws.poller.model.ExportFileTypeEnum org.lockss.util.rest.poller.model.ExportFileTypeEnum
fixResponseCode1234 $AUS_API_DELEGATE
